name: Go builder

on:
  push:
      branches: [ "main" ]
      paths:
        - code/backend/lambda/**
  pull_request:
      branches: [ "main" ]
      paths:
        - code/backend/lambda/**
#env:
  #Deploy_Route_Url: ${{secrets.AWS_DEPLOY_DEV_ENV}}
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: check setup
      run: |     
         go mod init backend-Go-Lambdas
         go mod tidy      
    - name: codebuld    
      run: |
        env GOOS=linux
        ##-----Build Module 1---------##
        echo *
        go build  'backend/lambda/create-news-item/main.go'
        go build  'backend/lambda/create-news-item/main.go'
        
        #--Zip the Build Files-----#
        zip create-news-item.zip create-news-item
        zip create-news-item.zip create-news-item
