name: Go builder

on:
  push:
    branches: [ "main" ]
    paths:
      - code/backend/lambda/**
env:
  Deploy_Route_Url: ${{secrets.AWS_DEPLOY_DEV_ENV}}
jobs:
 build:
  runs-on: ubuntu-latest
  strategy: 
    matrix:
      go-version: [1.22.1]
  steps:
   - name: check the code
     uses: actions/Checkout@v2     
   - name: test
     run: echo "tested"
   - name: setup go
     uses: actions/setup-go@v4
     with:
       go-version: ${{ matrix.go-version }}
     env:
      GO111MODULE: "on"
   - name: check setup
     run: |     
       go mod init backend-Go-Lambdas
       go mod tidy      
   - name: codebuld    
     run: |
      env GOOS=linux
      ##-----Build Module 1---------##
      go build  'backend/lambda/create-news-item/main.go'
      go build  'backend/lambda/create-news-item/main.go'
      
      #--Zip the Build Files-----#
      zip create-news-item.zip create-news-item
      zip create-news-item.zip create-news-item
