# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Lamda builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
      env:
        GO111MODULE: "on"
    - name: check setup
      run: |     
         go mod init backend-Go-Lambdas
         go mod tidy      
    - name: codebuld    
      run: |
        env GOOS=linux
        ##-----Build Module 1---------##
        go build -C backend/lamdas/get-news-items -o get-news-items 
        go build -C backend/lamdas/create-news-item -o create-news-item
        
        #--Zip the Build Files-----#
        zip get-news-items.zip backend/lamdas/get-news-items/get-news-items
        zip create-news-item.zip backend/lamdas/create-news-item/create-news-item

