# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      env:
        GO111MODULE: "on"
    - name: check setup
      run: |     
         go mod init backend-Go-Lambdas
         go mod tidy      
    - name: codebuld    
      run: |
        env GOOS=linux
        ##-----Build Module 1---------##
        cd backend/lamdas/get-news-items && go build -v .
        cd backend/lamdas/create-news-item && go build -v .
        
        #--Zip the Build Files-----#
        zip create-news-item.zip backend/lamdas/get-news-itemsget-news-items
        zip create-news-item.zip backend/lamdas/create-news-item/create-news-item

    - name: Test
      run: go test -v ./...
